<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find robot_description)/urdf/base/base.gazebo.xacro"/>

  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>
  
  <xacro:macro name="base_v0" params="parent *joint_origin">
	<joint name="base_link_joint" type="fixed">
	  <xacro:insert_block name="joint_origin"/>
	  <parent link="${parent}"/>
	  <child link="base_link"/>
	</joint>

	<link name="base_link">
	  <visual>
		<geometry>
		  <mesh filename="package://robot_description/meshes/DAE/base/base_link.dae"/>
		</geometry>
	  </visual>
	  <collision>
		<geometry>
		  <mesh filename="package://robot_description/meshes/STL/base/base_link.stl"/>
		</geometry>
	  </collision>
	  <inertial>
		<origin xyz="0 0 0.017"/>
		<mass value="1.2"/>
		<inertia ixx="0.0001873" ixy="0" ixz="0" iyy="0.000055" iyz="0" izz="0.0002283" />
	  </inertial>
	</link>

	<joint name="camera_joint" type="fixed">
      <origin xyz="0.064 -0.065 0.094" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="camera_link"/>
  	</joint>

  	<link name="camera_link">
      <visual>
     	<origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      	  <geometry>
       		<mesh filename="package://turtlebot3_description/meshes/sensors/r200.dae" />
      	  </geometry>
    	</visual>
      <collision>
    	<origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
      	<geometry>
          <box size="0.012 0.132 0.020"/>
      	</geometry>
      </collision>
	</link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>


  </xacro:macro>
  
</robot>
